### ISSUE TITLE
Unable to create subplots

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#107]
I have encountered a situation where I want to control the layout manually with subplots, but for some reason this is not possible with MCMCChains.  Here is an example that works outside of MCMCChains:

```
using StatsPlots
p = plot(layout=2)
density!(p,rand(10),subplot=1)
density!(p,rand(10),subplot=2)
```
This will produce two plots organized horizontally.  Here code to produce an analogous plot with an MCMCM chain: 

```
using MCMCChains,StatsPlots
# Define the experiment
n_iter = 500;
n_name = 3;
n_chain = 2;

# experiment results
val = randn(n_iter, n_name, n_chain) .+ [1, 2, 3]';
val = hcat(val, rand(1:2, n_iter, 1, n_chain));

# construct a Chains object
chn = Chains(val)
p = plot(layout=2)
density!(p,chn[:Param1],subplot=1)
density!(p,chn[:Param2],subplot=2)
```
In the later case, both densities are plotted in the first subplot.

**Comment by cpfiffer** [comment]
I believe this is because we enforce layouts/subplots for whole chains, even when you only end up using a single plot like the above. The offending lines are

https://github.com/TuringLang/MCMCChains.jl/blob/a69ceb4e6eaaef6585b55a15f8886e9213ac3654/src/plot.jl#L137

and

https://github.com/TuringLang/MCMCChains.jl/blob/a69ceb4e6eaaef6585b55a15f8886e9213ac3654/src/plot.jl#L144

I think I might be able to just not set subplots and layouts if you've only got one plot type.

**Comment by itsdfish** [comment]
Thanks for looking into this. I'm not sure what this entails for you or whether it conflicts with your goals. It would be nice to have the functionality because its consistent with how plots generally works. However, if its a hassle, I'll note for future reference I eventually settled on the following workaround:

`plot(plots...,layout=(n,m))` where `plots` is array of length m*m containing the subplots.

**Comment by cpfiffer** [comment]
No, I think this should probably be addressed internally. If you only actually spit out one plot, we shouldn't enforce layouts in any way. It's bad form. I think we'll continue to enforce layouts if you do something that prints out multiple plots, like just calling `plot(chain)` for example.
