### ISSUE TITLE
 MethodError for AxisArrays.AxisArray when creating chains

### ISSUE THREAD

**Issue by ashiklom** [TuringLang/MCMCChains.jl#212]
The following MCMCChains example code (lifted directly from the README)...

```julia
using MCMCChains
n_iter = 500
n_name = 3
n_chain = 2
val = randn(n_iter, n_name, n_chain) .+ [1, 2, 3]'
val = hcat(val, rand(1:2, n_iter, 1, n_chain))
chn = Chains(val)
```

...fails with the following error:

```
ERROR: MethodError: no method matching AxisArrays.AxisArray(::Array{Float64,3}; iter=1:1:500, var=["Param1", "Param2", "Param3", "Param4"], chain=1:2)
Closest candidates are:
  AxisArrays.AxisArray(::AbstractArray) at /Users/ashiklom/.julia/packages/AxisArrays/yhKAp/src/core.jl:231 got unsupported keyword arguments "iter", "var", "chain"
  AxisArrays.AxisArray(::D, ::Ax) where {T, N, D<:AbstractArray{T,N}, Ax<:Tuple{Vararg{AxisArrays.Axis,N}}} at /Users/ashiklom/.julia/packages/AxisArrays/yhKAp/src/core.jl:225 got unsupported keyword arguments "iter", "var", "chain"
  AxisArrays.AxisArray(::AbstractArray, ::Tuple{Vararg{AxisArrays.Axis,N} where N}) at /Users/ashiklom/.julia/packages/AxisArrays/yhKAp/src/core.jl:221 got unsupported keyword arguments "iter", "var", "chain"
  ...
Stacktrace:
 [1] Chains(::Array{Float64,3}, ::Array{String,1}, ::Dict{Symbol,Array{Any,1}}; start::Int64, thin::Int64, evidence::Missing, info::NamedTuple{(),Tuple{}}, sorted::Bool) at /Users/ashiklom/.julia/packages/MCMCChains/WWfCJ/src/chains.jl:84
 [2] Chains(::Array{Float64,3}, ::Array{String,1}, ::Dict{Symbol,Array{Any,1}}) at /Users/ashiklom/.julia/packages/MCMCChains/WWfCJ/src/chains.jl:31 (repeats 2 times)
 [3] top-level scope at REPL[11]:1
```

**Comment by devmotion** [comment]
As mentioned in https://github.com/TuringLang/Turing.jl/issues/1220#issuecomment-613692447, I assume you do not use the latest version of AxisArrays. Can you please post the output of
```julia
julia> ] add AxisArrays@0.4.2
```
if this is the case?

**Comment by ashiklom** [comment]
Thanks for the quick reply! Here is the output:

```
  Resolving package versions...
   Updating `~/projects/other/julia-experimentation/turing-mre/Project.toml`
  [39de3d68] + AxisArrays v0.4.2
   Updating `~/projects/other/julia-experimentation/turing-mre/Manifest.toml`
  [39de3d68] ↑ AxisArrays v0.4.0 ⇒ v0.4.2
  [8197267c] ↓ IntervalSets v0.5.0 ⇒ v0.4.0
```

My understanding of that is that an upgrade to `IntervalSets` led to a downgrade in `AxisArrays`.

**Comment by devmotion** [comment]
Interesting. Can you check if the example above works with the updated version of AxisArrays?

**Comment by ashiklom** [comment]
Yes, the above example now works correctly (with the `master` branch of this repo—I noticed you added the hard-coded version, thanks for the quick fix!).

Incidentally, I also noticed this change when installing MCMCChains from master:

```
  [80f14c24] ↓ AbstractMCMC v1.0.0 ⇒ v0.5.6
```

I'm assuming you're aware of this and/or it's deliberate, but just wanted to throw it up here just in case it was a surprise.

**Comment by devmotion** [comment]
Thanks! Hmm I don't quite understand why AbstractMCMC was downgraded when installing MCMCChains, since the CI tests for the latest commit use AbstractMCMC 1.0 successfully: https://travis-ci.com/github/TuringLang/MCMCChains.jl/jobs/319398984 Maybe there is some interaction with some other packages in your environment? BTW Turing is not compatible with AbstractMCMC 1.0 yet (not even the master branch), so if you have Turing among your installed packages this comes as no surprise.

**Comment by devmotion** [comment]
I still don't get why the old version of AxisArrays was installed in the first place, but since upgrading AxisArrays seems to have solved the issue and a new version of MCMCChains with the correct compatibility bounds (https://github.com/TuringLang/MCMCChains.jl/pull/213) is available through the registry now, I'll close this issue. Feel free to reopen if the problem persists or reoccurs!
