### ISSUE TITLE
summarystats rhat different from gelmandiag psrf?

### ISSUE THREAD

**Issue by mkarikom** [TuringLang/MCMCChains.jl#296]
I thought these were supposed to be the same but haven't read the paper(s) in a while?
Is this behavior intended?
```
using MCMCChains,DataFrames,Test

val = rand(500, 2, 3);
chn = Chains(val, [:a, :b],thin=2);

@test summarystats(chn)[:,:rhat] == gelmandiag(chn)[:,:psrf]

Test Failed at REPL[13]:1
  Expression: (summarystats(chn))[:, :rhat] == (gelmandiag(chn))[:, :psrf]
   Evaluated: [0.9986222285826325, 1.0002655998146657] == [0.9991946409488084, 1.0020782206705592]
```

**Comment by devmotion** [comment]
First of all, as a disclaimer, I am not very familiar with the implementation of `gelmandiag`, it's some old code and I assume it could be improved.

The implementation of Rhat and the effective sample size is based on the paper "Rank-normalization, folding, and localization: An improved Rhat for assessing convergence of MCMC" (https://arxiv.org/pdf/1903.08008.pdf) and the implementation in Stan (https://mc-stan.org/docs/2_26/reference-manual/effective-sample-size-section.html). Rhat is computed according to equation (4) in this paper and called "split-Rhat" by the authors since chains are split in half. Additionally, a correction factor (https://github.com/TuringLang/MCMCChains.jl/blob/9245cefe467e97f491a0b72f7e1b9ec17bc063cb/src/gelmandiag.jl#L42) is applied to the value in `gelmandiag`.

On a side note, MCMCChains supports 3 different methods for computing the effective sample size according to this paper, based on 3 different methods for estimating the autocorrelation:
- `ESSMethod` and `FFTESSMethod` are based on the estimator of the autocovariance in [Geyer, C. J. (1992). Practical Markov Chain Monte Carlo. Statistical Science, 473-483.](https://projecteuclid.org/euclid.ss/1177011137). The latter uses FFT for its computation (as done in Stan) but in my experience in most cases the "naive" computation is faster since the autocorrelation decreases so quickly and therefore only a few lags are needed. You have to load a package that implements the AbstractFFT.jl interface, such as FFTW.jl, if you want to use `FFTESSMethod`:
  ```julia
  julia> chain = Chains(rand(1000, 2, 4), [:a, :b]);

  julia> ess(chain) # `ESSMethod` is the default
  ESS
    parameters         ess      rhat 
        Symbol     Float64   Float64 

             a   3997.9684    0.9997
             b   4146.9360    0.9996

  julia> using FFTW

  julia> ess(chain; method=FFTESSMethod())
  ESS
    parameters         ess      rhat 
        Symbol     Float64   Float64 

             a   3997.9684    0.9997
             b   4146.9360    0.9996
  ```
- `BDAESSMethod` uses the variogram estimator discussed in BDA:
  ```julia
  julia> ess(chain; method=BDAESSMethod()) # same data
  ESS
    parameters         ess      rhat 
        Symbol     Float64   Float64 

             a   3983.7657    0.9997
             b   4130.5957    0.9996
  ```

**Comment by mkarikom** [comment]
Ok, that makes sense.  Thanks!
