### ISSUE TITLE
Rstar tests and doctests broken with MLJDecisionTreeInterface 0.3.1

### ISSUE THREAD

**Issue by sethaxen** [TuringLang/MCMCChains.jl#400]
The rstar test gives the traceback

```julia
R star test: Error During Test at /home/sethaxen/.julia/packages/MCMCChains/KaSPD/test/rstar_tests.jl:14
  Got exception outside of a @test
  MethodError: no method matching fit(::DecisionTreeClassifier, ::Int64, ::SubArray{Float64, 2, Matrix{Float64}, Tuple{Vector{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, ::SubArray{UInt32, 1, Vector{UInt32}, Tuple{Vector{Int64}}, false})
  
  Closest candidates are:
    fit(::DecisionTreeClassifier, ::Int64, ::Any, ::Any, ::Any, ::Any)
     @ MLJDecisionTreeInterface ~/.julia/packages/MLJDecisionTreeInterface/OtrDc/src/MLJDecisionTreeInterface.jl:45
    fit(::Supervised, ::Any, ::Any, ::Any, ::Any)
     @ MLJModelInterface ~/.julia/packages/MLJModelInterface/gw4ML/src/model_api.jl:16
    fit(::Resampler, ::Int64, ::Any...)
     @ MLJBase ~/.julia/packages/MLJBase/uxwHr/src/resampling.jl:1423
    ...
  
  Stacktrace:
    [1] rstar(rng::TaskLocalRNG, classifier::DecisionTreeClassifier, x::Matrix{Float64}, y::Vector{Int64}; subset::Float64, split_chains::Int64, verbosity::Int64)
      @ MCMCDiagnosticTools ~/.julia/packages/MCMCDiagnosticTools/4qFyf/src/rstar.jl:50
    [2] rstar(rng::TaskLocalRNG, classifier::DecisionTreeClassifier, x::Matrix{Float64}, y::Vector{Int64})
      @ MCMCDiagnosticTools ~/.julia/packages/MCMCDiagnosticTools/4qFyf/src/rstar.jl:22
    [3] rstar(classifier::DecisionTreeClassifier, x::Matrix{Float64}, y::Vector{Int64}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ MCMCDiagnosticTools ~/.julia/packages/MCMCDiagnosticTools/4qFyf/src/rstar.jl:217
    [4] rstar(classifier::DecisionTreeClassifier, x::Matrix{Float64}, y::Vector{Int64})
      @ MCMCDiagnosticTools ~/.julia/packages/MCMCDiagnosticTools/4qFyf/src/rstar.jl:216
    [5] macro expansion
      @ ~/.julia/packages/MCMCChains/KaSPD/test/rstar_tests.jl:16 [inlined]
    [6] macro expansion
      @ ~/.julia/juliaup/julia-1.9.0-beta4+0.x64.linux.gnu/share/julia/stdlib/v1.9/Test/src/Test.jl:1496 [inlined]
    [7] top-level scope
      @ ~/.julia/packages/MCMCChains/KaSPD/test/rstar_tests.jl:16
    [8] include(fname::String)
      @ Base.MainInclude ./client.jl:478
    [9] macro expansion
      @ ./timing.jl:273 [inlined]
   [10] macro expansion
      @ ~/.julia/packages/MCMCChains/KaSPD/test/runtests.jl:65 [inlined]
   [11] macro expansion
      @ ~/.julia/juliaup/julia-1.9.0-beta4+0.x64.linux.gnu/share/julia/stdlib/v1.9/Test/src/Test.jl:1496 [inlined]
   [12] top-level scope
      @ ~/.julia/packages/MCMCChains/KaSPD/test/runtests.jl:12
   [13] include(fname::String)
      @ Base.MainInclude ./client.jl:478
   [14] top-level scope
      @ none:6
   [15] eval
      @ ./boot.jl:370 [inlined]
   [16] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:280
   [17] _start()
      @ Base ./client.jl:522
  5.044218 seconds (7.89 M allocations: 516.767 MiB, 7.63% gc time, 82.44% compilation time: 27% of which was recompilation)
```

**Comment by devmotion** [comment]
Did I mention at some point that I'm annoyed by how often the MLJ integration is brokrn?

Did it not show up in the PRs? Did they use a different version of MLJXXX and is it due to some upstream changes?

**Comment by devmotion** [comment]
Missed that this issue showed up in MCMCChains, not MCMCDiagnosticTools. So forget my comment about PRs.

**Comment by ablaom** [comment]
Yes, this the MLJDecisionTreeInterface 0.3.1 release is breaking your case and should have been tagged as a new release. (This slipped by as very few clients interact with MLJ models directly through the model interface at MLJModelInterface.jl, which I assume is what you are doing.)

I will tag a new release and yank the old one. 

Generally, if you want to call the MLJModelInterface versions of `fit` and `predict` then you need to `reformat` the data you pass to those methods, so that the model-specific representation of the data is sent ([docs](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Implementing-a-data-front-end)). So everywhere you have
```
MLJModelInterface.fit(model, verbosity, data...)
```
I expect you want 
```
MLJModelInterface.fit(model, verbosity, MLJModelInterface.reformat(model, data)...)
```
And where you have
```
MLJModelInterface.predict(model, fitresult, X)
```
you want
```
MLJModelInterface.predict(model, fitresult, MLJModelInterface.reformat(model, X)...)`
```
These changes will be backwards compatible. The fallback for `reformat` just slurps the data. 

Tag me in any PR to repair and I can provide further guidance if there are difficulties.

**Comment by devmotion** [comment]
Thanks for the explanations and for taking action so promptly!

We already use `reformat` in MCMCDiagnosticTools 0.3.0/master: https://github.com/TuringLang/MCMCDiagnosticTools.jl/blob/5955f828f7539cfbb3acc072c03dff36c3ef5686/src/rstar.jl#L46-L49 MCMCChains is not yet compatible with that version (#401) but based on your comment it also seems that we use it incorrectly since 1) we `reformat` before calling `selectrows` and 2) we assume that `reformat` only returns a tuple of two elements. I guess the fix would be to call `selectrows` first and to not make any assumptions about how many values are returned? Of course, the same applies to the call of `predict` some lines below (https://github.com/TuringLang/MCMCDiagnosticTools.jl/blob/5955f828f7539cfbb3acc072c03dff36c3ef5686/src/rstar.jl#L53-L54).

**Comment by ablaom** [comment]
Mmm. Not sure.  `selectrows` is always applied to the model-specific representations of the data, i.e., is only applied to data that has been `reformat`ted. 

>  reformat only returns a tuple of two elements. 

It always returns a tuple, but the length of the tuple could be different from the length of `data` in `reformat(model, data...)`. So maybe that's the issue ?? because in the tree case the length grows.

**Comment by devmotion** [comment]
Hmm I think I have a rough idea but I'm also a bit confused after reading the docs (https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Summary-of-methods). There the `fit` method we call in MCMCDiagnosticTools (with only `model`, `verbosity`, X` and `y` but no other arguments) is listed as compulsory for supervised models. So that's not correct anymore?

Moreover, I noticed that in https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Implementing-a-data-front-end it is stated

> Important. reformat(model::SomeModelType, args...) must always return a tuple of the same length as args, even if this is one.

That doesn't seem to be correct either?

**Comment by ablaom** [comment]
> There the fit method we call in MCMCDiagnosticTools (with only model, verbosity, Xandy` but no other arguments) is listed as compulsory for supervised models. So that's not correct anymore?

It is compulsory that you implement `fit`. The signature should match what is being output by `reformat`, so the docs are misleading or wrong.  The signature of `reformat` is what the user supplies (in an MLJ machine, say), the form of data referred to in MLJ docstrings, and what traits like `input_scitype` are referring to.

> Important. reformat(model::SomeModelType, args...) must always return a tuple of the same length as args, even if this is one.

Oh bother, you are right! We have inadvertently broken that rule and I now recall the reason for it, which we will address in a [different way](https://github.com/JuliaAI/MLJBase.jl/issues/885). Please consider the rule amended: What is correct is that a tuple is always returned, even if that tuple has length one.
