### ISSUE TITLE
A chain to vector of `NamedTuple`s utility?

### ISSUE THREAD

**Issue by SamuelBrand1** [TuringLang/MCMCChains.jl#456]
Hi everyone!

Functions like `condition` and `generated_quantities` take `NamedTuples` as arguments (and `Dict`s). Sometimes this is really convenient, for example, in counter-factual modelling. Or in extending samples one model into a related model, e.g. for Bayesian forecasting.

However, I can't find a utility that maps between a chain object and an iterable object of `NamedTuples`. If it doesn't exist I think this would be a useful addition!

**Comment by SamuelBrand1** [comment]
PS in comparison to `get_params`, which is col wise with respect to the chain object, this would be row-wise.

**Comment by cpfiffer** [comment]
You might be able to use the Tables.jl interface here,
https://github.com/TuringLang/MCMCChains.jl/blob/master/src%2Ftables.jl,
though I'm not sure how current it is. Can you try 

using Tables rows(chain)
or maybe

using Tables rowtable(chain)
On May 22, 2024, GitHub ***@***.***> wrote:
> PS in comparison to get_params, which is col wise with respect to the
> chain object, this would be row-wise.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/TuringLang/MCMCChains.jl/issues/456#issuecomment-
2124558688>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AADHITQ54R3OVZN2Y6SVGYDZDR6FDAVCNFSM6AAAAABIDK4Y5SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRUGU2TQNRYHA>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by cpfiffer** [comment]
Cool, love it. Good to close?

**Comment by SamuelBrand1** [comment]
Would you want me to PR this utility to `MCMCChains`?

**Comment by SamuelBrand1** [comment]
```julia
using Tables
rowtable(chain)
```
Does indeed give an iterable with NamedTuples for samples. Very nice. Definitely using this pattern in the future.

**Comment by cpfiffer** [comment]
Thanks so much! Appreciate your time.
