### ISSUE TITLE
Error creating Chains from a chain object

### ISSUE THREAD

**Issue by jfmoulin** [TuringLang/MCMCChains.jl#64]
While reproducing the coin flipping example in the tuto [http://turing.ml/tutorials/0-introduction/](url) , trying to summarize the chain leads to an error:

    julia> chain
    Object of type Chains, with data of type 2000×7×1 Array{Union{Missing, Float64},3}

    Log evidence      = 0.0
    Iterations        = 1:2000
    Thinning interval = 1
    Chains            = 1
    Samples per chain = 2000
    internals         = elapsed, epsilon, eval_num, lf_eps, lf_num, lp
    parameters        = p

    parameters
       Mean    SD   Naive SE  MCSE    ESS  
    p 0.8335 0.0128   0.0003 0.0018 48.5404

    julia> p_summary = MCMCChain.Chains(chain[:p])
    ERROR: MethodError: no method matching MCMCChain.Chains(::MCMCChains.Chains{Union{Missing,Float64},Float64,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:hashedsummary,),Tuple{Base.RefValue{Tuple{UInt64,MCMCChains.ChainSummaries}}}}})
    Closest candidates are:
    MCMCChain.Chains(::T<:Real, ::Array{Union{Missing, T<:Real},3}, ::AbstractRange{Int64}, ::Array{T,1} where T, ::Dict{Symbol,Int64}, ::Array{Int64,1}) where T<:Real at /home/jfmoulin/.julia/packages/MCMCChain/PSRXh/src/MCMCChain.jl:35
      MCMCChain.Chains(::Array{T<:Real,3}; start, thin, names, uniquenames, chains) where T<:Real at /home/jfmoulin/.julia/packages/MCMCChain/PSRXh/src/chains.jl:13
    MCMCChain.Chains(::Array{Union{Missing, T<:Real},3}; start, thin, names, uniquenames, chains) where T<:Real at /home/jfmoulin/.julia/packages/MCMCChain/PSRXh/src/chains.jl:31
      ...
    Stacktrace:
    [1] top-level scope at none:0

**Comment by cpfiffer** [comment]
Sorry, the tutorials are currently being rewritten to handle some breaking changes made to the MCMCChains syntax. You can adjust the tutorial by changing the line 

```julia
p_summary = MCMCChain.Chains(chain[:p])
``` 

to

```julia
p_summary = chain[:p]
```

Let me know if that works for you. Sorry for the inconvenience.

**Comment by jfmoulin** [comment]
Thanks, this does work!
Now, where could I find a trace of the chi2 or of log_evidence?
is it related to :

    chain.value[:,end-1]

Actually what are lf_num and lf_eps?

Thanks for the nice work, with such a fast answer do not be sorry about the inconvenience ;0)

**Comment by cpfiffer** [comment]
If you want to see a trace plot of log evidence, `chn[:lp]` will make a new chain containing only the log evidence parameter. You can plot a trace using

```julia
plot(chn[:lp])
```

The values are in the chain, but they're hidden away in a "section" called `:internals`. You can show everything in a chain using `describe(chn, showall=true)` or show some specific section using `describe(chn, section = :internals)`. Most functions in `MCMCChains` (including `plot`) support the `showall` and `section` keywords.

I don't actually know exactly what `lf_num` and `lf_eps` are exactly. Someone else who works the samplers might know better (@xukai92 maybe).

Anyways, I'm going to close this for the moment since the tutorial has been updated on the site and in the repo.

**Comment by uferc** [comment]
Sorry for commenting on a closed thread, google lead me here because I was trying to find out about model comparison possibilities and log evidence. I tried out the things posted here however they do not work. Are both functions, the `describe() `and `plot(chn[:lp])` no longer supported? 
I get an error message "MethodError: no method matching mcse_bm(::Vector{Float64}; showall=true)".
